Composition {
	CurrentTime = 4688,
	RenderRange = { 0, 5000 },
	GlobalRange = { 0, 5000 },
	CurrentID = 943,
	Version = "Fusion 8.0 build 23",
	SavedOutputs = 1,
	HeldTools = 0,
	DisabledTools = 0,
	LockedTools = 0,
	AudioOffset = 0,
	Resumable = true,
	OutputClips = {
		"/Users/jjolton/neural_vis/test.mov"
	},
	Tools = {
		Loader5 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/Dropbox/shape_image_set/project_plates/01_nodes/part5_end/frame00049.png",
					FormatID = "PNGFormat",
					Length = 50,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 0,
					ExtendFirst = 125,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 0,
					GlobalEnd = 125
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { -66, 26 } },
		},
		Loader6 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/Dropbox/shape_image_set/project_plates/01_nodes/part1/frame00000.png",
					FormatID = "PNGFormat",
					Length = 133,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 131,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 140,
					GlobalEnd = 271
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 493, 66 } },
		},
		Loader7 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/Dropbox/shape_image_set/project_plates/01_nodes/part2/frame00000.png",
					FormatID = "PNGFormat",
					Length = 50,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 49,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 272,
					GlobalEnd = 321
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 603, 65 } },
		},
		Loader8 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/Dropbox/shape_image_set/project_plates/01_nodes/part3/frame00000.png",
					FormatID = "PNGFormat",
					Length = 133,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 132,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 321,
					GlobalEnd = 453
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 711, 65 } },
		},
		Loader9 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/Dropbox/shape_image_set/project_plates/01_nodes/part4/frame00000.png",
					FormatID = "PNGFormat",
					Length = 50,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 49,
					ExtendFirst = 0,
					ExtendLast = 10,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 453,
					GlobalEnd = 512
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 819, 65 } },
		},
		Loader10 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/Dropbox/shape_image_set/project_plates/01_nodes/part5_0/frame00000.png",
					FormatID = "PNGFormat",
					Length = 25,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 24,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 512,
					GlobalEnd = 536
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 925, 65 } },
		},
		Loader11 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/Dropbox/shape_image_set/project_plates/01_nodes/part5_1/frame00000.png",
					FormatID = "PNGFormat",
					Length = 25,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 24,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 536,
					GlobalEnd = 560
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 1033, 64 } },
		},
		Loader12 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/Dropbox/shape_image_set/project_plates/01_nodes/part5_2/frame00000.png",
					FormatID = "PNGFormat",
					Length = 25,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 24,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 560,
					GlobalEnd = 584
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 1137, 65 } },
		},
		Loader13 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/Dropbox/shape_image_set/project_plates/01_nodes/part5_3/frame00000.png",
					FormatID = "PNGFormat",
					Length = 25,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 24,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 584,
					GlobalEnd = 608
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 1245, 64 } },
		},
		Loader14 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/Dropbox/shape_image_set/project_plates/01_nodes/part5_4/frame00000.png",
					FormatID = "PNGFormat",
					Length = 25,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 24,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 608,
					GlobalEnd = 632
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 1352, 64 } },
		},
		Loader15 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/Dropbox/shape_image_set/project_plates/01_nodes/part5_5/frame00000.png",
					FormatID = "PNGFormat",
					Length = 25,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 24,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 632,
					GlobalEnd = 656
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 1457, 65 } },
		},
		Loader16 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/Dropbox/shape_image_set/project_plates/01_nodes/part5_6/frame00000.png",
					FormatID = "PNGFormat",
					Length = 25,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 24,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 656,
					GlobalEnd = 680
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 1567, 62 } },
		},
		Loader17 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/Dropbox/shape_image_set/project_plates/01_nodes/part5_7/frame00000.png",
					FormatID = "PNGFormat",
					Length = 25,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 24,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 680,
					GlobalEnd = 704
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 1674, 65 } },
		},
		Loader18 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/Dropbox/shape_image_set/project_plates/01_nodes/part5_8/frame00000.png",
					FormatID = "PNGFormat",
					Length = 25,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 24,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 704,
					GlobalEnd = 728
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 1780, 64 } },
		},
		Loader19 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/Dropbox/shape_image_set/project_plates/01_nodes/part5_9/frame00000.png",
					FormatID = "PNGFormat",
					Length = 25,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 24,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 728,
					GlobalEnd = 752
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 1887, 65 } },
		},
		Loader20 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/Dropbox/shape_image_set/project_plates/01_nodes/part5_end/frame00000.png",
					FormatID = "PNGFormat",
					Length = 50,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 49,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 752,
					GlobalEnd = 801
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 1992, 64 } },
		},
		Loader21 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/Dropbox/shape_image_set/project_plates/01_nodes/part6/frame00000.png",
					FormatID = "PNGFormat",
					Length = 250,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 249,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 802,
					GlobalEnd = 1051
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 2100, 66.1729 } },
		},
		Loader22 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/george_bush_classifier/network/full_color_images/George_W_Bush_0001.jpg",
					FormatID = "JpegFormat",
					StartFrame = 1,
					Length = 530,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 20,
					ExtendFirst = 300,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 1350,
					GlobalEnd = 1670
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 2522.25, 16.9733 } },
		},
		Loader22_1 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/george_bush_classifier/network/full_color_images/Andre_Agassi_0001.jpg",
					FormatID = "JpegFormat",
					StartFrame = 1,
					Length = 36,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 20,
					ExtendFirst = 250,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 1400,
					GlobalEnd = 1670
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 2629.92, 16.5214 } },
		},
		Loader22_1_1 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/george_bush_classifier/network/full_color_images/Arnold_Schwarzenegger_0001.jpg",
					FormatID = "JpegFormat",
					StartFrame = 1,
					Length = 42,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 20,
					ExtendFirst = 200,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 1450,
					GlobalEnd = 1670
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 2739.25, 17.356 } },
		},
		Loader23 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/neural_vis/shape_images_for_training/triangle0000.png",
					FormatID = "PNGFormat",
					Length = 500,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 20,
					ExtendFirst = 150,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 1500,
					GlobalEnd = 1670
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 2843.74, 14.4696 } },
		},
		Loader23_1 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/neural_vis/shape_images_for_training/square0000.png",
					FormatID = "PNGFormat",
					Length = 500,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 20,
					ExtendFirst = 100,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 1550,
					GlobalEnd = 1670
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 2949.73, 14.4012 } },
		},
		Loader23_1_1 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/neural_vis/shape_images_for_training/circle0000.png",
					FormatID = "PNGFormat",
					Length = 500,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 20,
					ExtendFirst = 50,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 1600,
					GlobalEnd = 1670
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 3057.39, 13.5667 } },
		},
		Loader24 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/neural_vis/galaxies/full_color/000000008.jpg",
					FormatID = "JpegFormat",
					StartFrame = 8,
					Length = 9970,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 300,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 1700,
					GlobalEnd = 2000
				}
			},
			Inputs = {
				MissingFrames = Input { Value = 1, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 3271.03, 45.3487 } },
		},
		Loader25 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/neural_vis/galaxies/hi/0008.png",
					FormatID = "PNGFormat",
					StartFrame = 8,
					Length = 9970,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 940,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 2060,
					GlobalEnd = 3000
				}
			},
			Inputs = {
				MissingFrames = Input { Value = 1, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 3375.18, -16.41 } },
		},
		Loader24_1 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/neural_vis/galaxies/full_color/000000008.jpg",
					FormatID = "JpegFormat",
					StartFrame = 8,
					Length = 9970,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 940,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 2060,
					GlobalEnd = 3000
				}
			},
			Inputs = {
				MissingFrames = Input { Value = 1, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 3479.5, 45.8004 } },
		},
		Loader29 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/neural_vis/letter_images_for_training/c_default0000.png",
					FormatID = "PNGFormat",
					Length = 1000,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 290,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 3060,
					GlobalEnd = 3350
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 3578.98, 258.166 } },
		},
		Loader28 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/neural_vis/letter_images_for_training/b_default0000.png",
					FormatID = "PNGFormat",
					Length = 1000,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 290,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 3060,
					GlobalEnd = 3350
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 3475.5, 241.475 } },
		},
		Loader27 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/neural_vis/letter_images_for_training/a_default0000.png",
					FormatID = "PNGFormat",
					Length = 1000,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 290,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 3060,
					GlobalEnd = 3350
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 3477.17, 205.588 } },
		},
		Loader29_1 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/neural_vis/letter_images_for_training/z_default0000.png",
					FormatID = "PNGFormat",
					Length = 1000,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 150,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 3350,
					GlobalEnd = 3500
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 3694.14, 353.519 } },
		},
		Loader28_1 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/neural_vis/letter_images_for_training/y_default0000.png",
					FormatID = "PNGFormat",
					Length = 1000,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 150,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 3350,
					GlobalEnd = 3500
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 3589.31, 330.143 } },
		},
		Loader27_1 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/neural_vis/letter_images_for_training/x_default0000.png",
					FormatID = "PNGFormat",
					Length = 1000,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 150,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 3350,
					GlobalEnd = 3500
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 3590.98, 294.257 } },
		},
		Loader26 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/Dropbox/shape_image_set/final/inputImg_1.png",
					FormatID = "PNGFormat",
					StartFrame = 1,
					Length = 509,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 508,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 3900,
					GlobalEnd = 4408
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 4032.34, 107.563 } },
		},
		Loader30 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/Dropbox/shape_image_set/final/inputImg_1.png",
					FormatID = "PNGFormat",
					StartFrame = 1,
					Length = 509,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 400,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 4600,
					GlobalEnd = 5000
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 4255.57, 107.563 } },
		},
		Loader4 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/neural_vis/gradient_ascent_images/generated/0.png",
					FormatID = "PNGFormat",
					Length = 500,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 499,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 0,
					GlobalEnd = 499
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 2996, 328 } },
		},
		Loader1 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/neural_vis/data/gradients/intercept/hidden_output_1.png",
					FormatID = "PNGFormat",
					StartFrame = 1,
					Length = 500,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 499,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 0,
					GlobalEnd = 499
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 2484.36, 531.336 } },
		},
		Loader2 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/neural_vis/data/gradients/images_coef/hidden_output_1.png",
					FormatID = "PNGFormat",
					StartFrame = 1,
					Length = 500,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 499,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 0,
					GlobalEnd = 499
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 2483.36, 494.336 } },
		},
		Loader3 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/Users/jjolton/neural_vis/gradient_ascent_images/generated/0.png",
					FormatID = "PNGFormat",
					Length = 500,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 499,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 1,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 0,
					GlobalEnd = 499
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 2878.36, 563.336 } },
		},
		Background1 = Background {
			Inputs = {
				GlobalOut = Input { Value = 5000, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Gradient = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { -178, 108 } },
		},
		Transform3 = Transform {
			Inputs = {
				Center = Input { Value = { 0.569702197361772, 0.558659217877095 }, },
				Size = Input { Value = 0.59047619047619, },
				Input = Input {
					SourceOp = "Loader5",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -66, 67 } },
		},
		Merge6 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Transform3",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -66, 108 } },
		},
		Text1 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalOut = Input { Value = 125, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.527773644794921, 0.854692974532576 }, },
				Size = Input { Value = 0.0666666666666667, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "The Subtle Intricacies of\n", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 49, 67 } },
		},
		Merge5 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge6",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text1",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 49, 108 } },
		},
		Text3 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalOut = Input { Value = 125, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.514450974557357, 0.741872648358422 }, },
				Size = Input { Value = 0.0976190476190476, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "Neural Networks", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 161, 68 } },
		},
		Merge2 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge5",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text3",
					Source = "Output",
				},
				Center = Input { Value = { 0.515473887814313, 0.520618556701031 }, },
				Size = Input { Value = 1.11428571428571, },
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 161, 108 } },
		},
		Text2 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalOut = Input { Value = 125, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.534816247582205, 0.362513198563996 }, },
				Size = Input { Value = 0.0619047619047619, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "a scientific visualization by:", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 273, 67 } },
		},
		Merge3 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text2",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 273, 108 } },
		},
		Text4 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalOut = Input { Value = 125, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.527079303675048, 0.18985510376471 }, },
				Size = Input { Value = 0.0523809523809524, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "Austin Cerny,\nJared Jolton, and\nPaul Salminen", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 383, 67 } },
		},
		Merge4 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge3",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text4",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 383, 108 } },
		},
		Merge7 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Loader6",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 493, 108 } },
		},
		Text5 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 155, },
				GlobalOut = Input { Value = 260, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.385880077369439, 0.146048109965636 }, },
				Size = Input { Value = 0.0619047619047619, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "These little blue spheres are ", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 493, 232 } },
		},
		Text6 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 155, },
				GlobalOut = Input { Value = 260, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.820562338813669, 0.155431462390225 }, },
				Size = Input { Value = 0.0928571428571429, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "neurons", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Red1 = Input { Value = 0, },
				Green1 = Input { Value = 0.0901960784313725, },
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 379, 231 } },
		},
		Merge11 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Text5",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text6",
					Source = "Output",
				},
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 493, 193 } },
		},
		Merge8 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge7",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Merge11",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 493, 151 } },
		},
		Merge9 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge8",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Loader7",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 603, 108 } },
		},
		Text8 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 285, },
				GlobalOut = Input { Value = 321, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.525145067698259, 0.72680412371134 }, },
				Size = Input { Value = 0.0738095238095, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "are very similar to real                 \nin the brain", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 718, 465 } },
		},
		Text6_1_1 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 285, },
				GlobalOut = Input { Value = 321, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.805609284332689, 0.778362365209148 }, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "neurons", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Red1 = Input { Value = 0, },
				Green1 = Input { Value = 0.0901960784313725, },
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 603, 502 } },
		},
		Merge28 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Text8",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text6_1_1",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 603, 464 } },
		},
		Text7 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 285, },
				GlobalOut = Input { Value = 321, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.517408123791102, 0.88831615120275 }, },
				Size = Input { Value = 0.0738095238095238, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "The                 in this visualization ", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 716, 428 } },
		},
		Merge27 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge28",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text7",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 604, 428 } },
		},
		Text6_1 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 285, },
				GlobalOut = Input { Value = 321, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.31431334622824, 0.891752577319588 }, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "neurons", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Red1 = Input { Value = 0, },
				Green1 = Input { Value = 0.0901960784313725, },
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 718, 392 } },
		},
		Merge26 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge27",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text6_1",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 604, 392 } },
		},
		Merge25 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge9",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Merge26",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 602, 152 } },
		},
		Merge10 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge25",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Loader8",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 711, 108 } },
		},
		Text6_2 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 330, },
				GlobalOut = Input { Value = 410, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.205475298194713, 0.18979572355861 }, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "neurons", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Red1 = Input { Value = 0, },
				Green1 = Input { Value = 0.0901960784313725, },
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 716, 362 } },
		},
		Text10 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 330, },
				GlobalOut = Input { Value = 410, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.867504835589942, 0.190721649484536 }, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "layers", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Green1 = Input { Value = 0.866666666666667, },
				Blue1 = Input { Value = 0.243137254901961, },
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 826, 335 } },
		},
		Merge31 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Text6_2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text10",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 713, 335 } },
		},
		Text9 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 330, },
				GlobalOut = Input { Value = 410, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.559961315280464, 0.190721649484536 }, },
				Size = Input { Value = 0.0714285714285714, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "are organized into ", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 827, 304 } },
		},
		Merge30 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge31",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text9",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 713, 304 } },
		},
		Merge29 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge10",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Merge30",
					Source = "Output",
				},
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 712, 151 } },
		},
		Merge12 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge29",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Loader9",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 819, 108 } },
		},
		Text12 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 425, },
				GlobalOut = Input { Value = 500, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.82495164410058, 0.768965517241379 }, },
				Size = Input { Value = 0.07, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "network", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Red1 = Input { Value = 0.654901960784314, },
				Green1 = Input { Value = 0.0862745098039216, },
				Blue1 = Input { Value = 0.76078431372549, },
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 819, 261 } },
		},
		Text11 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 425, },
				GlobalOut = Input { Value = 500, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.496131528046422, 0.768965517241379 }, },
				Size = Input { Value = 0.06, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "are stacked to form a", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 927, 226 } },
		},
		Merge34 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Text12",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text11",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 820, 225 } },
		},
		Text10_1 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 425, },
				GlobalOut = Input { Value = 500, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.194390715667311, 0.77692854603626 }, },
				Size = Input { Value = 0.07, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "layers", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Green1 = Input { Value = 0.866666666666667, },
				Blue1 = Input { Value = 0.243137254901961, },
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 926, 188 } },
		},
		Merge33 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge34",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text10_1",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 820, 188 } },
		},
		Merge32 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge12",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Merge33",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 820, 150 } },
		},
		Merge13 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge32",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Loader10",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 925, 108 } },
		},
		Merge14 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge13",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Loader11",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 1033, 108 } },
		},
		Text14 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 525, },
				GlobalOut = Input { Value = 600, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.772727272727273, 0.841379310344828 }, },
				Size = Input { Value = 0.07, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "synapses", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Green1 = Input { Value = 0.141176470588235, },
				Blue1 = Input { Value = 0.113725490196078, },
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 1034, 264 } },
		},
		Text13 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 525, },
				GlobalOut = Input { Value = 600, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.469052224371373, 0.837931034482759 }, },
				Size = Input { Value = 0.06, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "are connected by", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 1149, 227 } },
		},
		Merge37 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Text14",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text13",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 1034, 226 } },
		},
		Text10_1_1 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 525, },
				GlobalOut = Input { Value = 600, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.207930367504836, 0.842445787415571 }, },
				Size = Input { Value = 0.07, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "layers", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Green1 = Input { Value = 0.866666666666667, },
				Blue1 = Input { Value = 0.243137254901961, },
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 1148, 188 } },
		},
		Merge36 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge37",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text10_1_1",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 1034, 188 } },
		},
		Merge35 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge14",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Merge36",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 1034, 153 } },
		},
		Merge15 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge35",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Loader12",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 1137, 108 } },
		},
		Merge16 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge15",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Loader13",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 1245, 108 } },
		},
		Merge17 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge16",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Loader14",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 1352, 108 } },
		},
		Text14_1 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 610, },
				GlobalOut = Input { Value = 690, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.352998065764023, 0.913793103448276 }, },
				Size = Input { Value = 0.07, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "synapse", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Green1 = Input { Value = 0.141176470588235, },
				Blue1 = Input { Value = 0.113725490196078, },
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 1352, 255 } },
		},
		Text13_1 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 610, },
				GlobalOut = Input { Value = 690, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.513539651837524, 0.86551724137931 }, },
				Size = Input { Value = 0.06, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "each                   has a                value \nassociated with it", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 1467, 218 } },
		},
		Merge37_1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Text14_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text13_1",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 1352, 217 } },
		},
		Text10_1_1_1 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 610, },
				GlobalOut = Input { Value = 690, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.668278529980658, 0.914859580519019 }, },
				Size = Input { Value = 0.07, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "weight", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Red1 = Input { Value = 0.254901960784314, },
				Green1 = Input { Value = 0.788235294117647, },
				Blue1 = Input { Value = 0.690196078431373, },
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 1466, 179 } },
		},
		Merge36_1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge37_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text10_1_1_1",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 1352, 179 } },
		},
		Merge35_1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge17",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Merge36_1",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 1352, 144 } },
		},
		Merge18 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge35_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Loader15",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 1457, 109 } },
		},
		Merge19 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge18",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Loader16",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 1567, 109 } },
		},
		Merge20 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge19",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Loader17",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 1675, 109 } },
		},
		Merge21 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge20",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Loader18",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 1781, 109 } },
		},
		Merge22 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge21",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Loader19",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 1886, 109 } },
		},
		Text10_1_1_2_1 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 715, },
				GlobalOut = Input { Value = 740, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.82495164410058, 0.818082711221709 }, },
				Size = Input { Value = 0.07, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "layers", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Green1 = Input { Value = 0.866666666666667, },
				Blue1 = Input { Value = 0.243137254901961, },
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 1879.78, 329.105 } },
		},
		Text6_1_1_1_1 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 715, },
				GlobalOut = Input { Value = 740, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.318181818181819, 0.816234150965754 }, },
				Size = Input { Value = 0.07, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "neurons", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Red1 = Input { Value = 0, },
				Green1 = Input { Value = 0.0901960784313725, },
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 1994.12, 293.218 } },
		},
		Merge39 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Text10_1_1_2_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text6_1_1_1_1",
					Source = "Output",
				},
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 1878.95, 294.052 } },
		},
		Text6_1_1_1 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 715, },
				GlobalOut = Input { Value = 740, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.264023210831722, 0.902441047517478 }, },
				Size = Input { Value = 0.07, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "neurons", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Red1 = Input { Value = 0, },
				Green1 = Input { Value = 0.0901960784313725, },
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 1994.17, 262.165 } },
		},
		Merge38 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge39",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text6_1_1_1",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 1878.95, 263.173 } },
		},
		Text13_1_1 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 715, },
				GlobalOut = Input { Value = 740, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.530947775628627, 0.858585140419481 }, },
				Size = Input { Value = 0.06, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "all                   in a             are connected to \nall                   in any adjacent              ", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 1994, 229 } },
		},
		Merge37_1_1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge38",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text13_1_1",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 1879, 228 } },
		},
		Text10_1_1_2 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 715, },
				GlobalOut = Input { Value = 740, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.527079303675048, 0.907737883635502 }, },
				Size = Input { Value = 0.07, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "layer", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Green1 = Input { Value = 0.866666666666667, },
				Blue1 = Input { Value = 0.243137254901961, },
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 1994.95, 189.73 } },
		},
		Merge36_1_1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge37_1_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text10_1_1_2",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 1879, 190 } },
		},
		Merge35_1_1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge22",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Merge36_1_1",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 1879, 155 } },
		},
		Merge23 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge35_1_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Loader20",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 1992, 109 } },
		},
		Merge24 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge23",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Loader21",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 2101, 109 } },
		},
		Text15 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 1100, },
				GlobalOut = Input { Value = 1200, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.532882011605416, 0.5 }, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "Leveraging this simple structure, \n", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 2205.27, 65.378 } },
		},
		Merge40 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge24",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text15",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 2206.1, 109.611 } },
		},
		Text16 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 1140, },
				GlobalOut = Input { Value = 1200, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.515473887814313, 0.420689655172414 }, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "we can teach computers to see!", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 2309.59, 65.378 } },
		},
		Merge43 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge40",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text16",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 2310.43, 108.776 } },
		},
		Merge41 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge43",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 2415.59, 108.776 } },
		},
		Text12_1 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 1230, },
				GlobalOut = Input { Value = 1330, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.735976789168278, 0.673136627562507 }, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "network", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Red1 = Input { Value = 0.654901960784314, },
				Green1 = Input { Value = 0.0862745098039216, },
				Blue1 = Input { Value = 0.76078431372549, },
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 2415.59, 213.098 } },
		},
		Text17 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 1230, },
				GlobalOut = Input { Value = 1330, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "We trained a neural                to\nclassify several different\n types of images,\nsuch as faces and shapes", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 2522.41, 182.219 } },
		},
		Merge45 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Text12_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text17",
					Source = "Output",
				},
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 2416.43, 182.219 } },
		},
		Merge44 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge41",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Merge45",
					Source = "Output",
				},
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 2416.43, 142.994 } },
		},
		Resize1 = BetterResize {
			Inputs = {
				Width = Input { Value = 500, },
				Height = Input { Value = 500, },
				PixelAspect = Input { Value = { 1, 1 }, },
				Input = Input {
					SourceOp = "Loader22",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 2521.58, 47.8527 } },
		},
		Transform4 = Transform {
			Inputs = {
				Center = Input { Value = { -0.768289209811204, 1.02476624310717 }, },
				Input = Input {
					SourceOp = "Resize1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 2522.41, 75.3935 } },
		},
		Merge42 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge44",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Transform4",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 2523.25, 107.56 } },
		},
		Resize1_1 = BetterResize {
			Inputs = {
				Width = Input { Value = 500, },
				Height = Input { Value = 500, },
				PixelAspect = Input { Value = { 1, 1 }, },
				Input = Input {
					SourceOp = "Loader22_1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 2629.25, 47.4008 } },
		},
		Transform4_1 = Transform {
			Inputs = {
				Center = Input { Value = { 0.500646960401564, 1.02476624310717 }, },
				Input = Input {
					SourceOp = "Resize1_1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 2630.08, 74.9416 } },
		},
		Merge42_2 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge42",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Transform4_1",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 2630.08, 107.108 } },
		},
		Resize1_1_1 = BetterResize {
			Inputs = {
				Width = Input { Value = 500, },
				Height = Input { Value = 500, },
				PixelAspect = Input { Value = { 1, 1 }, },
				Input = Input {
					SourceOp = "Loader22_1_1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 2738.58, 48.2354 } },
		},
		Transform4_1_1 = Transform {
			Inputs = {
				Center = Input { Value = { 1.75958635434096, 1.02143964378057 }, },
				Input = Input {
					SourceOp = "Resize1_1_1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 2739.41, 75.7762 } },
		},
		Merge42_2_1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge42_2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Transform4_1_1",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 2739.41, 107.942 } },
		},
		Resize2 = BetterResize {
			Inputs = {
				Width = Input { Value = 500, },
				Height = Input { Value = 500, },
				PixelAspect = Input { Value = { 1, 1 }, },
				Input = Input {
					SourceOp = "Loader23",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 2844.57, 41.1761 } },
		},
		Transform5 = Transform {
			Inputs = {
				Center = Input { Value = { -0.762669245647969, -0.0595876288659791 }, },
				Input = Input {
					SourceOp = "Resize2",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 2845.41, 74.1761 } },
		},
		Merge42_1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge42_2_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Transform5",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 2846.24, 107.176 } },
		},
		Resize2_1 = BetterResize {
			Inputs = {
				Width = Input { Value = 500, },
				Height = Input { Value = 500, },
				PixelAspect = Input { Value = { 1, 1 }, },
				Input = Input {
					SourceOp = "Loader23_1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 2950.56, 41.1077 } },
		},
		Transform5_1 = Transform {
			Inputs = {
				Center = Input { Value = { 0.500000000000001, -0.0596388197653748 }, },
				Input = Input {
					SourceOp = "Resize2_1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 2951.4, 74.1077 } },
		},
		Merge42_1_1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge42_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Transform5_1",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 2952.23, 107.108 } },
		},
		Resize2_1_1 = BetterResize {
			Inputs = {
				Width = Input { Value = 500, },
				Height = Input { Value = 500, },
				PixelAspect = Input { Value = { 1, 1 }, },
				Input = Input {
					SourceOp = "Loader23_1_1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 3058.22, 40.2732 } },
		},
		Transform5_1_1 = Transform {
			Inputs = {
				Center = Input { Value = { 1.07191489361702, -0.0596388197653749 }, },
				Input = Input {
					SourceOp = "Resize2_1_1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 3059.06, 73.2732 } },
		},
		Merge42_1_1_1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge42_1_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Transform5_1_1",
					Source = "Output",
				},
				Center = Input { Value = { 0.677949709864603, 0.5 }, },
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 3059.06, 106.273 } },
		},
		Merge47 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge42_1_1_1",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 3164.21, 105.055 } },
		},
		Text12_1_1 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 1800, },
				GlobalOut = Input { Value = 1900, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.716634429400386, 0.24021803531224 }, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "network", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Red1 = Input { Value = 0.654901960784314, },
				Green1 = Input { Value = 0.0862745098039216, },
				Blue1 = Input { Value = 0.76078431372549, },
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 3164.21, 205.588 } },
		},
		Text18 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 1800, },
				GlobalOut = Input { Value = 1900, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.490328820116054, 0.182758620689655 }, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "We also taught the               to\nclassify images of galaxies", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 3273.37, 169.701 } },
		},
		Merge49 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Text12_1_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text18",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 3164.21, 169.701 } },
		},
		Merge48 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge47",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Merge49",
					Source = "Output",
				},
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 3165.04, 136.318 } },
		},
		Transform6 = Transform {
			Inputs = {
				Size = Input { Value = 2.56190476190476, },
				Input = Input {
					SourceOp = "Loader24",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 3270.19, 72.8898 } },
		},
		Merge46 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge48",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Transform6",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 3271.03, 105.89 } },
		},
		Crop1 = Crop {
			Inputs = {
				XOffset = Input { Value = 144, },
				YOffset = Input { Value = 54, },
				XSize = Input { Value = 352, },
				YSize = Input { Value = 372, },
				KeepCentered = Input { Value = 1, },
				Input = Input {
					SourceOp = "Loader25",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 3375.35, 16.59 } },
		},
		Transform7 = Transform {
			Inputs = {
				Center = Input { Value = { 1.31818181818182, 1.20353170189099 }, },
				Size = Input { Value = 1.91428571428571, },
				Input = Input {
					SourceOp = "Crop1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 3376.18, 47.0179 } },
		},
		Transform8 = Transform {
			Inputs = {
				Center = Input { Value = { 0.0182657567242068, 1.0797007156799 }, },
				Size = Input { Value = 1.68571428571429, },
				Input = Input {
					SourceOp = "Loader24_1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 3480.34, 75.8452 } },
		},
		Merge51 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Transform7",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Transform8",
					Source = "Output",
				},
				Center = Input { Value = { -0.515473887814314, 0.5 }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 3375.35, 75.4619 } },
		},
		Merge50 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge46",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Merge51",
					Source = "Output",
				},
				Center = Input { Value = { 0.571566731141199, 0.413129517715369 }, },
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 3376.18, 105.958 } },
		},
		Text12_1_1_1 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 2160, },
				GlobalOut = Input { Value = 2760, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.780464216634429, 0.247090887545917 }, },
				Size = Input { Value = 0.065, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "network", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Red1 = Input { Value = 0.654901960784314, },
				Green1 = Input { Value = 0.0862745098039216, },
				Blue1 = Input { Value = 0.76078431372549, },
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 3377.02, 202.249 } },
		},
		Text19 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 2160, },
				GlobalOut = Input { Value = 2760, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.490328820116054, 0.200213295414148 }, },
				Size = Input { Value = 0.06, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "To normalize the input to the                ,\nwe filtered the images ", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 3483.01, 170.987 } },
		},
		Merge54 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Text12_1_1_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text19",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 3376.18, 170.535 } },
		},
		Merge52 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge50",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Merge54",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 3376.18, 139.656 } },
		},
		Text20 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 2830, },
				GlobalOut = Input { Value = 2900, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.5, 0.173539518900344 }, },
				Size = Input { Value = 0.06, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "The edge detecting filters\nattempt to mimic the output \nof retinal bipolar cells", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 3482.17, 140.108 } },
		},
		Merge53 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge52",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text20",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 3481.34, 108.394 } },
		},
		Text12_1_1_1_1_1 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 3130, },
				GlobalOut = Input { Value = 3300, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.298839458413926, 0.887415570565232 }, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "network", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Red1 = Input { Value = 0.654901960784314, },
				Green1 = Input { Value = 0.0862745098039216, },
				Blue1 = Input { Value = 0.76078431372549, },
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 3585.65, 32.8303 } },
		},
		Text22 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 3130, },
				GlobalOut = Input { Value = 3300, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.534816247582205, 0.493103448275862 }, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "the                was very successful\n\n\n\n\n\nlearning to classify the\nalphabet visually", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 3692.48, 68.7172 } },
		},
		Merge63 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Text12_1_1_1_1_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text22",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 3586.49, 70.3863 } },
		},
		Merge61 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge53",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Merge63",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 3584.83, 107.942 } },
		},
		Merge64 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Loader29",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Loader28",
					Source = "Output",
				},
				Center = Input { Value = { -0.745214700193424, 0.507448275862066 }, },
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 3580.66, 228.122 } },
		},
		Merge65 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge64",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Loader27",
					Source = "Output",
				},
				Center = Input { Value = { -1.99265764023211, 0.514998933522929 }, },
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 3582.32, 193.069 } },
		},
		Merge62 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge61",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Merge65",
					Source = "Output",
				},
				Center = Input { Value = { 0.826885880077369, 0.540644626140538 }, },
				Size = Input { Value = 5, },
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 3583.16, 139.656 } },
		},
		Merge61_1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge62",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 3697.31, 185.917 } },
		},
		Merge64_1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Loader29_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Loader28_1",
					Source = "Output",
				},
				Center = Input { Value = { -0.745214700193424, 0.507448275862066 }, },
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 3694.47, 316.79 } },
		},
		Merge65_1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge64_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Loader27_1",
					Source = "Output",
				},
				Center = Input { Value = { -1.99265764023211, 0.514998933522929 }, },
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 3694.8, 273.718 } },
		},
		Merge62_1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge61_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Merge65_1",
					Source = "Output",
				},
				Center = Input { Value = { 0.826885880077369, 0.541237113402062 }, },
				Size = Input { Value = 5, },
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 3695.64, 217.631 } },
		},
		Merge55 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge62_1",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 3816.37, 184.474 } },
		},
		Text10_1_1_1_1 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 3560, },
				GlobalOut = Input { Value = 3860, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.819148936170213, 0.442445787415571 }, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "weights", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Red1 = Input { Value = 0.254901960784314, },
				Green1 = Input { Value = 0.788235294117647, },
				Blue1 = Input { Value = 0.690196078431373, },
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 3814.71, 353.059 } },
		},
		Text14_1_1 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 3560, },
				GlobalOut = Input { Value = 3860, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.451644100580271, 0.444827586206897 }, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "synapses", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Green1 = Input { Value = 0.141176470588235, },
				Blue1 = Input { Value = 0.113725490196078, },
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 3919.86, 320.511 } },
		},
		Merge60 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Text10_1_1_1_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text14_1_1",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 3814.71, 318.841 } },
		},
		Text12_1_1_1_1 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 3560, },
				GlobalOut = Input { Value = 3860, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.596711798839458, 0.552932811944542 }, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "network", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Red1 = Input { Value = 0.654901960784314, },
				Green1 = Input { Value = 0.0862745098039216, },
				Blue1 = Input { Value = 0.76078431372549, },
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 3920.69, 287.629 } },
		},
		Merge59 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge60",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text12_1_1_1_1",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 3813.87, 285.458 } },
		},
		Text21 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 3560, },
				GlobalOut = Input { Value = 3860, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "Through visualization, \nwe can find out exactly \nhow the                 \nuses its                  and             \nto learn how to recognize these\nimages", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 3920.69, 251.241 } },
		},
		Merge58 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge59",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text21",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 3813.87, 251.24 } },
		},
		Merge56 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge55",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Merge58",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 3813.87, 219.527 } },
		},
		Transform9 = Transform {
			Inputs = {
				Center = Input { Value = { -1.54255319148936, 0.917525773195876 }, },
				Size = Input { Value = 4.27619047619048, },
				Input = Input {
					SourceOp = "Loader26",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 4032.34, 140.981 } },
		},
		Merge57 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge56",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Transform9",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 4032.48, 181.299 } },
		},
		Text6_1_1_1_2 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 3960, },
				GlobalOut = Input { Value = 4200, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.426499032882012, 0.187664415215073 }, },
				Size = Input { Value = 0.065, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "neuron", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Red1 = Input { Value = 0, },
				Green1 = Input { Value = 0.0901960784313725, },
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 4043.03, 404.314 } },
		},
		Text12_1_1_1_1_2 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 3960, },
				GlobalOut = Input { Value = 4200, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.728239845261121, 0.181798791325986 }, },
				Size = Input { Value = 0.065, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "network", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Red1 = Input { Value = 0.654901960784314, },
				Green1 = Input { Value = 0.0862745098039216, },
				Blue1 = Input { Value = 0.76078431372549, },
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 4157.98, 358.865 } },
		},
		Merge70 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Text6_1_1_1_2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text12_1_1_1_1_2",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 4044.36, 361.539 } },
		},
		Text10_1_1_1_1_1 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 3960, },
				GlobalOut = Input { Value = 4200, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.720502901353966, 0.951036852707667 }, },
				Size = Input { Value = 0.065, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "weight", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Red1 = Input { Value = 0.254901960784314, },
				Green1 = Input { Value = 0.788235294117647, },
				Blue1 = Input { Value = 0.690196078431373, },
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 4156.65, 318.764 } },
		},
		Merge69 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge70",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text10_1_1_1_1_1",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 4039.02, 317.427 } },
		},
		Text23 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 3960, },
				GlobalOut = Input { Value = 4200, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.52321083172147, 0.52405498281787 }, },
				Size = Input { Value = 0.06, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "These plots represent the              values\n\n\n\n\n\n\n\n\nof a               in the             \nwhile it learns to recognize letters", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 4147.29, 270.642 } },
		},
		Merge68 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge69",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text23",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 4039.02, 270.642 } },
		},
		Merge66 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge57",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Merge68",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 4033.67, 226.531 } },
		},
		Text24 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 4430, },
				GlobalOut = Input { Value = 4600, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.52321083172147, 0.5 }, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "These plots suggest \nsomething interesting", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 4147.3, 142.318 } },
		},
		Merge67 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge66",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text24",
					Source = "Output",
				},
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 4144.62, 183.756 } },
		},
		Resize3 = BetterResize {
			Inputs = {
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				PixelAspect = Input { Value = { 1, 1 }, },
				Input = Input {
					SourceOp = "Loader30",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 4255.57, 146.328 } },
		},
		Merge71 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge67",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Resize3",
					Source = "Output",
				},
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 4254.24, 182.419 } },
		},
		Text10_1_1_1_1_1_1 = TextPlus {
			ExtentSet = true,
			Inputs = {
				GlobalIn = Input { Value = 4600, },
				GlobalOut = Input { Value = 4800, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.368471953578337, 0.847588576845598 }, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "weights", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Red1 = Input { Value = 0.254901960784314, },
				Green1 = Input { Value = 0.788235294117647, },
				Blue1 = Input { Value = 0.690196078431373, },
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 4258.25, 294.703 } },
		},
		Text25 = TextPlus {
			ExtentSet = true,
			CtrlWZoom = false,
			Inputs = {
				GlobalIn = Input { Value = 4600, },
				GlobalOut = Input { Value = 4800, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.490328820116054, 0.844827586206897 }, },
				Font = Input { Value = "Arial", },
				StyledText = Input { Value = "the               appear to be", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 4374.54, 255.938 } },
		},
		Merge73 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Text10_1_1_1_1_1_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text25",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 4258.25, 257.275 } },
		},
		Merge72 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge71",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Merge73",
					Source = "Output",
				},
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 4255.57, 219.847 } },
		},
		Merge74 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge72",
					Source = "Output",
				},
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 4370.53, 182.419 } },
		},
		Saver1 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/Users/jjolton/neural_vis/test.mov",
						FormatID = "QuickTimeMovies",
						Length = 0,
						Multiframe = true,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "QuickTimeMovies" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				["QuickTimeMovies.Compression"] = Input { Value = FuID { "H.264_avc1" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 3634.08, -349.407 } },
		},
		Transform1 = Transform {
			Inputs = {
				Input = Input {
					SourceOp = "Loader1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 2604.36, 531.336 } },
		},
		Transform2 = Transform {
			Inputs = {
				Angle = Input { Value = -90.0636962503638, },
				Input = Input {
					SourceOp = "Loader2",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 2604.36, 494.336 } },
		},
		Merge1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Transform1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Transform2",
					Source = "Output",
				},
				ApplyMode = Input { Value = FuID { "Screen" }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 2725.36, 531.336 } },
		}
	},
	Views = {
		{
			FrameTypeID = "ChildFrame",
			Mode = 3,
			LayoutPreset = 0,
			Left = 0,
			Top = 27,
			Width = 1280,
			Height = 670,
			Views = ordered() {
				Main = MultiView {
					Active = "Flow",
					ViewList = ordered() {
						Flow = "FlowView",
						Console = "ConsoleView",
						Timeline = "TimelineView",
						Spline = "SplineEditorView",
						Info = "InfoView",
						Chat = "ChatView"
					},
					Flow = FlowView {
						Flags = {
							Navigator = true,
							AutoHideNavigator = true,
							AutoSnap = true,
							RemoveRouters = true
						},
						NavigatorSize = { 200, 140 },
						Direction = "Horizontal",
						PipeStyle = "Direct",
						Scale = 0.748103,
						Offset = { -3496.32, -48.7475 }
					},
					Timeline = TimelineView {
						TreeControlState = {
						},
						DisplayMode = "All Tools",
						ShowCurrentTimeTools = false,
						Filter = "Show All",
						ShowSelectedTools = false,
						ShowAnimatedToolsOnly = false,
						ShowEditBoxes = false,
						KeyFrameView = {
							Position = { Left = 150, Bottom = 247 },
							ScaleX = 6.4327485380117,
							OffsetX = -147.953216374269,
							OffsetY = 0,
							AutoScaling = "scroll",
							AutoSnapTo = "frame",
							AutoSnapToGuidelines = false,
							GuidelinesGrabEnabled = true,
							GuidelinesSnapTo = "none"
						},
						Spreadsheet = { LeftPos = 150, Visible = false }
					},
					Spline = SplineEditorView {
						LeftPos = 256,
						ScaleX = 0.2,
						ScaleY = 0.00338983050847458,
						OffsetX = 2225.2,
						OffsetY = 0,
						AutoScaling = "scroll",
						AutoSnapTo = "frame",
						AutoSnapToGuidelines = false,
						GuidelinesSnapTo = "frame",
						ShowKeyMarkers = false,
						IndependentHandles = false,
						ShowNonSplineModifiers = false,
						GuidelinesGrabEnabled = true,
						ShowOneToolOnly = false,
						ShowSelectedTools = false,
						ShowAllInputs = false,
						Filter = "Show All"
					},
				},
				Controls = MultiView {
					Active = "Tools",
					ViewList = ordered() {
						Tools = "ControlView",
						Modifiers = "ModifierView"
					},
				},
				Left = "PreviewContainer",
				Right = "PreviewContainer",
				Transport = "TransportView",
				Time = "TimeView"
			},
			Layout = {
				Columns = 2,
				RatioX = 1,
				RatioY = 1,
				{
					Rows = 3,
					RatioX = 0.749803921568627,
					RatioY = 0.0104790419161677,
					{
						Columns = 2,
						RatioX = 1,
						RatioY = 0.515105740181269,
						{ ID = "Left", RatioX = 0.544596012591815, RatioY = 0.00879765395894428, Pop = true },
						{ ID = "Right", RatioX = 0.455403987408185, Pop = true },
						Pop = true
					},
					{ ID = "Main", RatioY = 0.397280966767372, Pop = true },
					{ ID = "Time", SnapY = 56, Flat = true }
				},
				{
					Rows = 2,
					PixelX = 317,
					{ ID = "Controls", RatioX = 1, RatioY = 1 },
					{ ID = "Transport", FixedY = -2 }
				}
			}
		}
	},
	Prefs = {
		Comp = {
			Views = {
				Right = {
					Viewer = {
						ScaleMode = 1,
					},
				},
				Left = {
					Viewer = {
						Channel = 4294967295,
						ScaleMode = 1,
						Smooth = false,
					},
				},
				View1 = {
				},
			},
			FrameFormat = {
				GuideRatio = 1.77777777777778,
			},
			LastFile = "/Users/jjolton/neural_vis/data/gradients/images_coef/input_hidden_1.png",
			PolyKeyListDlg = {
				Window = {
					Left = 587,
					Top = 110
				}
			},
			Unsorted = {
				GlobalEnd = 5000,
				RenderSettings = {
					Configs = {
						Final = {
							StepRender = false,
							PriorityClasses = "local",
							SizeType = 1,
							MotionBlur = true,
							CustomAspect = true,
							CustomHeight = 240,
							ShowSlaves = false,
							CustomWidth = 320,
							StepSize = 5,
							UpdateMode = "Some",
							UseNetwork = false,
							Quality = true
						},
						Preview = {
							StepRender = false,
							PriorityClasses = "local",
							SizeType = 1,
							MotionBlur = true,
							CustomAspect = true,
							CustomHeight = 240,
							ShowSlaves = false,
							CustomWidth = 320,
							StepSize = 5,
							UpdateMode = "Some",
							UseNetwork = false,
							Quality = false
						}
					},
					PreviewConfig = "Preview",
					CurrentConfig = "Final"
				}
			},
			Paths = {
			},
			QuickTime = {
			},
		}
	}
}

 